name: Test GITHUB_TOKEN Permissions

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-token:
    runs-on: ubuntu-latest

    steps:
      - name: Create Issue via GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo "Testing token on repo $REPO"

          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/issues \
            -d '{"title":"✅ Token Verified","body":"This issue confirms that the `GITHUB_TOKEN` has write access."}'
